#############################################################
# +-------------------------------------------------------+ #
# |                  EssentialsX Discord                  | #
# +-------------------------------------------------------+ #
#############################################################

# This is the config file for EssentialsXDiscord.
# This config was generated for version ${full.version}.

# You need to create a bot user in order to connect your server to Discord.
# You can find instructions on this here: #TODO write up docs

# The token for your bot from the Discord Developers site.
token: "INSERT-TOKEN-HERE"

# The ID of your server.
# #TODO tutorial
guild: 000000000000000000

# Defined text channels
# Channels defined here can be used for two different purposes;
#
# Firstly, channels defined here can be used to give players permission to see messages from said channel.
# This can be done by give your players the permission node `essentials.discord.receive.<channel>`
# For example, if you wanted to let a player see messages from the primary channel, you'd give them `essentials.discord.receive.primary`
#
# Secondly, channels defined here can be used in the section below to specify which channel a message goes to
# If a defined channel id is invalid, the primary channel will be used as a fallback
# If the primary channel is not defined or invalid, the default channel of the server will be used
# If your server doesn't have any text channels, the plugin will be disabled
# By default, two channels are defined; (You will need to replace the zeros with the actual channel id you want to use)
# - primary, which will send basic join/leave/death/chat messages
# - staff, which will send kick/mute messages
channels:
  primary: 000000000000000000
  staff: 000000000000000000

# Determine which discord channels certain messages will be sent to
# You can either use the names of the channels listed above or just the id of a channel.
# If an invalid channel is used, the primary channel will be used instead
#
# To disable a message from showing, use 'none' as the channel name
message-types:
  # Join messages sent when a player joins the minecraft server
  join: primary
  # Leave messages sent when a player leaves the minecraft server
  leave: primary
  # Chat messages sent when a player chats on the minecraft server
  chat: primary
  # Death messages sent when a player dies on the minecraft server
  death: primary
  # Message sent when a player is kicked from the minecraft server
  kick: staff
  # Message sent when a player's mute state is changed on the minecraft server
  mute: staff

# The presence of the bot, including its status, activity and status message
presence:
  # The online status of the bot. Must be one of the following;
  # * "online" - Shows as green circle (Online)
  # * "idle" - Shows as yellow half-circle (Away)
  # * "dnd" - Shows as red circle (Do Not Disturb)
  # * "invisible" - Makes the bot appear offline
  status: online
  # The activity of the bot to be prefixed before your message below. Must be one of the following;
  # * "playing" - Shows up as "Playing <message>"
  # * "listening" - Shows up as "Listening to <message>"
  # * "watching" - Shows up as "Watching <message>"
  # * "competing" - Shows up as "Competing in <message>"
  # * "custom" - Just Shows the message defined below
  # * "none" - Don't show any activity message
  activity: "playing"
  # The activity status message
  message: "Minecraft"